# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-18 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
