# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-19 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0002_sighting_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=b''),
        ),
    ]
