# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-19 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0002_auto_20160518_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='image',
            field=models.ImageField(default='', upload_to=b''),
            preserve_default=False,
        ),
    ]
