# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-24 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0003_sighting_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_scientific', models.CharField(max_length=100)),
                ('family_english', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus', models.CharField(max_length=100)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birds.Family')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subspecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subspecies', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='location',
        ),
        migrations.RemoveField(
            model_name='species',
            name='species_name',
        ),
        migrations.AddField(
            model_name='sighting',
            name='caption',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='sighting',
            name='lat',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='sighting',
            name='lng',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='species',
            name='species',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='image',
            field=models.ImageField(default=None, upload_to=b''),
        ),
        migrations.AddField(
            model_name='subspecies',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birds.Species'),
        ),
        migrations.AddField(
            model_name='family',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birds.Order'),
        ),
        migrations.AddField(
            model_name='sighting',
            name='subspecies',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='birds.Subspecies'),
        ),
        migrations.AddField(
            model_name='species',
            name='genus',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='birds.Genus'),
        ),
    ]
