# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-20 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0003_auto_20160719_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='sighting_date',
            field=models.DateField(),
        ),
    ]
