# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-24 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0004_auto_20160524_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sighting',
            name='species',
        ),
        migrations.AddField(
            model_name='subspecies',
            name='common_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
