# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-14 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0005_auto_20160524_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='species_tags',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='subspecies',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='birds.Subspecies'),
        ),
        migrations.AlterField(
            model_name='subspecies',
            name='common_name',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
