# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-01 18:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='post_ts',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 1, 18, 28, 24, 793493, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
