# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-02 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0006_sighting_post_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='viewed_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
