# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-17 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0007_speciesfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='species_english',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
