# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-03 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0007_comment_viewed_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='post_text',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
