# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-17 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0008_species_species_english'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subspecies',
            name='common_name',
        ),
    ]
