# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-03 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0008_sighting_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
