# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-15 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0009_remove_subspecies_common_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='subspecies',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='birds.Subspecies'),
        ),
    ]
