# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-04 18:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('birds', '0011_auto_20160803_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='sighting',
            old_name='subspecies',
            new_name='species_tag',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='species_tags',
        ),
        migrations.AddField(
            model_name='speciesvotes',
            name='sighting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birds.Sighting'),
        ),
        migrations.AddField(
            model_name='speciesvotes',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birds.Subspecies'),
        ),
        migrations.AddField(
            model_name='speciesvotes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
