# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-08 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0012_auto_20160804_1855'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpeciesVotes',
            new_name='SpeciesVote',
        ),
    ]
