# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-10 20:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('birds', '0013_auto_20160808_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesSuggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sighting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birds.Sighting')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birds.Subspecies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
