# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0015_auto_20160829_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='birdphoto',
            name='order',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sighting',
            name='sighting_date',
            field=models.DateField(null=True),
        ),
    ]
