# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0016_auto_20160829_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='caption',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='lat',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='lng',
            field=models.FloatField(default=None, null=True),
        ),
    ]
