# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0020_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uid',
            name='user',
        ),
        migrations.DeleteModel(
            name='Uid',
        ),
    ]
