# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-29 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0023_birdphoto_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='caption',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
    ]
