# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-15 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0025_speciessuggestions_accetpted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speciessuggestions',
            old_name='accetpted',
            new_name='accepted',
        ),
    ]
