# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-31 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0026_auto_20170115_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='birdphoto',
            name='medium_url',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='caption',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
