# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-10 17:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('birds', '0029_avatar_thumbnail_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiet', models.BooleanField(default=False)),
                ('caption', models.CharField(max_length=50)),
                ('msg', models.CharField(max_length=200)),
                ('not_ts', models.DateTimeField(auto_now_add=True)),
                ('sighting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birds.Sighting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
